### ISSUE TITLE
prune-previews job is failing on the scheduled nightly job

### ISSUE THREAD

**Issue by raulcd** [ursacomputing/crossbow#62]
The prune-previews job has been failing for some time:
https://github.com/ursacomputing/crossbow/actions/runs/5873883476/job/15927782695
```
Run actions/github-script@v5
  with:
    script: let prs = "                            13933                             35312                             36591                             36840                             36943                             36946                             37121                             apache-arrow-13.0.0 ".split(" ").filter(x => x)
  async function not_open(id) {
   try {
      let pr = await github.rest.pulls.get({
      "owner": "apache",
      "repo": "arrow",
      "pull_number": id
      })
    }
    catch(err) {
      # In case of error retrieving PR try to clean it.
      # Example manually triggered job with different naming.
      return(id)
    }
    if(pr.data.state !== "open") {
      return(id)
    }
    return("")
  }
  
  let del_prs = await Promise.all(prs.map(not_open))
  del_prs = del_prs.filter(x => x).join(" ")
  console.log(`::set-output name=del_prs::${del_prs}`)
  
    github-token: ***
    debug: false
    user-agent: actions/github-script
    result-encoding: json
  env:
    PRs:                             13933                             35312                             36591                             36840                             36943                             36946                             37121                             apache-arrow-13.0.0 
SyntaxError: Invalid or unexpected token
Error: Unhandled error: SyntaxError: Invalid or unexpected token
    at new AsyncFunction (<anonymous>)
    at callAsyncFunction (/home/runner/work/_actions/actions/github-script/v5/dist/index.js:4888:16)
    at main (/home/runner/work/_actions/actions/github-script/v5/dist/index.js:4943:26)
    at Module.272 (/home/runner/work/_actions/actions/github-script/v5/dist/index.js:4927:1)
    at __webpack_require__ (/home/runner/work/_actions/actions/github-script/v5/dist/index.js:24:31)
    at startup (/home/runner/work/_actions/actions/github-script/v5/dist/index.js:43:19)
    at /home/runner/work/_actions/actions/github-script/v5/dist/index.js:49:18
    at Object.<anonymous> (/home/runner/work/_actions/actions/github-script/v5/dist/index.js:52:10)
    at Module._compile (node:internal/modules/cjs/loader:1105:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1159:10)
```

**Comment by raulcd** [comment]
@assignUser any idea?
