### ISSUE TITLE
Error Generating performance report for 16.0.0

### ISSUE THREAD

**Issue by raulcd** [ursacomputing/crossbow#84]
I job failed when generating the Performance Report comparison between 16.0.0 and 15.0.2 RC3:
```
Quitting from lines 351-369 [compute-process-micro-bm-data] (performance-release-report.qmd)
Error in `rename_with()` at dplyr/R/mutate.R:146:2:
! Names must be unique.
✖ These names are duplicated:
  * "unit" at locations 3 and 79.
Backtrace:
  1. ... %>% ...
 26. dplyr:::rename_with.data.frame(., ~gsub("baseline.tags.", "", .))
       at dplyr/R/rename.R:84:2
Warning messages:
1: Unknown or uninitialised column: `baseline`. 
2: Unknown or uninitialised column: `contender`. 
Execution halted
ERROR: Error
    at renderFiles (file:///opt/quarto/bin/quarto.js:77074:29)
    at eventLoopTick (ext:core/01_core.js:183:11)
    at async render (file:///opt/quarto/bin/quarto.js:81807:21)
    at async Command.fn (file:///opt/quarto/bin/quarto.js:81954:32)
    at async Command.execute (file:///opt/quarto/bin/quarto.js:8104:13)
    at async quarto (file:///opt/quarto/bin/quarto.js:114968:5)
    at async file:///opt/quarto/bin/quarto.js:114986:9
```
This is the job failure: https://github.com/ursacomputing/crossbow/actions/runs/8750575039/job/24014381152

**Comment by raulcd** [comment]
@boshek @assignUser
